/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/paname-spot.def.ts
 * Command: astryx theme build src/theme/paname-spot.def.ts
 * CLI: @astryxdesign/cli@0.4.6
 * Core: @astryxdesign/core@0.4.6
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const panameSpotTheme: DefinedTheme;
