name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: mustapha-smail-org/deployment-workflows/.github/workflows/ci-release.yml@main
    with:
      service-name: frontend
      automation-app-id: ${{ vars.AUTOMATION_APP_ID }}
    secrets:
      automation-app-private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
